package inspect

import (
	"hash/crc32"
	"net/http"
	"net/url"
	"regexp"
	"sort"
	"strings"
)

var (
	titleRX   = regexp.MustCompile(`(?is)<title[^>]*>(.*?)</title>`)
	emailRX   = regexp.MustCompile(`[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}`)
	privIPRX  = regexp.MustCompile(`\b(?:10\.(?:\d{1,3}\.){2}\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|172\.(?:1[6-9]|2\d|3[01])\.\d{1,3}\.\d{1,3})\b`)
	dirListRX = regexp.MustCompile(`(?i)<title>\s*Index of /|<h1>\s*Index of /|Directory listing for /`)
	versionRX = regexp.MustCompile(`\d+\.\d+`)
)

type errSig struct {
	name string
	rx   *regexp.Regexp
}

var errorSigs = []errSig{
	{"PHP error", regexp.MustCompile(`(?i)<b>(Warning|Fatal error|Notice|Parse error)</b>|on line <b>\d+|Stack trace:|Uncaught (Exception|Error)`)},
	{"Python traceback", regexp.MustCompile(`Traceback \(most recent call last\)|File ".+", line \d+, in`)},
	{"Django debug page", regexp.MustCompile(`(?i)You're seeing this error because you have <code>DEBUG = True|DisallowedHost|django\.core`)},
	{"Java stack trace", regexp.MustCompile(`(?i)javax?\.[a-z.]+Exception|at [a-z0-9_.]+\([A-Za-z0-9_]+\.java:\d+\)|org\.springframework`)},
	{"ASP.NET error", regexp.MustCompile(`(?i)Server Error in '.*' Application|System\.[A-Za-z.]+Exception|Microsoft \.NET Framework`)},
	{"Ruby/Rails error", regexp.MustCompile(`(?i)ActionController|ActiveRecord::|app/controllers/|rails\.root`)},
	{"Node/Express error", regexp.MustCompile(`(?i)at Object\.<anonymous>|node_modules|Error: .+\n\s+at .+\(`)},
	{"SQL error", regexp.MustCompile(`(?i)SQL syntax|SQLSTATE\[|ORA-\d{5}|Unclosed quotation mark|PostgreSQL.*ERROR|sqlite3?\.OperationalError`)},
	{"Generic stack trace", regexp.MustCompile(`(?i)stack ?trace|backtrace|debug mode`)},
}

type wafSig struct {
	name   string
	header string // header substring marker (lower)
	cookie string // cookie substring marker (lower)
	body   string // body substring marker (lower)
}

var wafSigs = []wafSig{
	{"Cloudflare", "cloudflare", "__cfduid", "attention required! | cloudflare"},
	{"Cloudflare", "cf-ray", "cf_clearance", ""},
	{"Akamai", "akamaighost", "ak_bmsc", ""},
	{"Sucuri", "x-sucuri-id", "", "access denied - sucuri website firewall"},
	{"Imperva Incapsula", "x-iinfo", "incap_ses", "incapsula incident"},
	{"Imperva Incapsula", "", "visid_incap", ""},
	{"F5 BIG-IP ASM", "", "bigipserver", "the requested url was rejected"},
	{"AWS WAF", "awselb", "aws-waf-token", ""},
	{"ModSecurity", "mod_security", "", "this error was generated by mod_security"},
	{"Barracuda", "barracuda", "barra_counter_session", ""},
	{"Wordfence", "", "", "generated by wordfence"},
	{"Fastly", "fastly", "", ""},
}

func detectWAF(headers map[string]string, cookies []string, body string) string {
	hblob := strings.ToLower(headerBlob(headers))
	cblob := strings.ToLower(strings.Join(cookies, " "))
	lbody := strings.ToLower(body)
	if len(lbody) > 200000 {
		lbody = lbody[:200000]
	}
	for _, w := range wafSigs {
		if w.header != "" && strings.Contains(hblob, w.header) {
			return w.name
		}
		if w.cookie != "" && strings.Contains(cblob, w.cookie) {
			return w.name
		}
		if w.body != "" && strings.Contains(lbody, w.body) {
			return w.name
		}
	}
	return ""
}

func headerBlob(h map[string]string) string {
	var sb strings.Builder
	for k, v := range h {
		sb.WriteString(k)
		sb.WriteByte(':')
		sb.WriteString(v)
		sb.WriteByte('\n')
	}
	return sb.String()
}

var sensitiveMarkers = []string{".env", ".git/config", ".git/head", ".htpasswd", "wp-config.php.bak",
	"id_rsa", ".aws/credentials", "config.php.bak", ".sql", ".bak", "/.svn/", "docker-compose", ".npmrc"}

func isSensitivePath(low string) bool {
	for _, m := range sensitiveMarkers {
		if strings.Contains(low, m) {
			return true
		}
	}
	return false
}

func flatten(h http.Header) map[string]string {
	out := make(map[string]string, len(h))
	for k, v := range h {
		out[k] = strings.Join(v, ", ")
	}
	return out
}

func resolve(base, ref string) string {
	b, err := url.Parse(base)
	if err != nil {
		return ""
	}
	r, err := url.Parse(strings.TrimSpace(ref))
	if err != nil {
		return ""
	}
	return b.ResolveReference(r).String()
}

func cloneValues(v url.Values) url.Values {
	out := url.Values{}
	for k, vals := range v {
		cp := make([]string, len(vals))
		copy(cp, vals)
		out[k] = cp
	}
	return out
}

func squish(s string) string {
	s = strings.NewReplacer("\n", " ", "\r", " ", "\t", " ").Replace(strings.TrimSpace(s))
	for strings.Contains(s, "  ") {
		s = strings.ReplaceAll(s, "  ", " ")
	}
	if len(s) > 120 {
		s = s[:120] + "…"
	}
	return s
}

func snippet(s string, start, n int) string {
	if start > len(s) {
		return ""
	}
	end := start + n
	if end > len(s) {
		end = len(s)
	}
	out := strings.Map(func(r rune) rune {
		if r == '\n' || r == '\r' || r == '\t' {
			return ' '
		}
		if r < 32 {
			return -1
		}
		return r
	}, s[start:end])
	out = strings.TrimSpace(out)
	for strings.Contains(out, "  ") {
		out = strings.ReplaceAll(out, "  ", " ")
	}
	return out
}

func crc32hex(b []byte) string {
	h := crc32.ChecksumIEEE(b)
	const hex = "0123456789abcdef"
	out := make([]byte, 8)
	for i := 0; i < 8; i++ {
		out[7-i] = hex[h&0xf]
		h >>= 4
	}
	return string(out)
}

func tlsVersion(v uint16) string {
	switch v {
	case 0x0300:
		return "SSLv3"
	case 0x0301:
		return "TLS1.0"
	case 0x0302:
		return "TLS1.1"
	case 0x0303:
		return "TLS1.2"
	case 0x0304:
		return "TLS1.3"
	}
	return "unknown"
}

func approxEqual(a, b int) bool {
	d := a - b
	if d < 0 {
		d = -d
	}
	tol := b / 20
	if tol < 32 {
		tol = 32
	}
	return d <= tol
}

func capList(in []string, n int) []string {
	if len(in) > n {
		return in[:n]
	}
	return in
}

func uniqCap(in []string, n int) []string {
	seen := map[string]bool{}
	var out []string
	for _, x := range in {
		x = strings.ToLower(x)
		if !seen[x] {
			seen[x] = true
			out = append(out, x)
		}
	}
	sort.Strings(out)
	return capList(out, n)
}
